package com.enums;

public enum ConfigProperties {
    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOTS,
    FAILEDSTEPSSCREENSHOTS,
    SKIPPEDSTEPSSCREENSHOTS,
    RUNMODE,
    SELENIUMGRIDURL,
    BROWSER
}
